### ISSUE TITLE
Create a CSP Distance Class/Method

### ISSUE THREAD

**Issue by Julian88Tex** [lovinghouston/lwcgoogleplacesbutton#1]
As an admin, I want to get a list of potential Accounts as CSP records based on a given Account.

ACs

Given this apex script is provided [TBD from @sungysang]
And a Account ID is provided
And Account is Type = Church
And the Mailing Zip code is filled in
When executed in Dev Console Anonymous Apex
Then a list of 100 or less records are returned in debug logs
And all records are from Google places search
And all records are schools
And all records are sorted from closest to furthest based on Distance

Given this apex script is provided [TBD from @sungysang]
And a Account ID is provided
And Account is Type = School
And the Mailing Zip code is filled in
When executed in Dev Console Anonymous Apex
Then a list of 100 or less records are returned in debug logs
And all records are from Google places search
And all records are churches
And all records are sorted from closest to furthest based on Distance

Given this apex script is provided [TBD from @sungysang]
And no Account ID is provided
When executed in Dev Console Anonymous Apex
Then an error is given in console "Please provide an account ID."

**Comment by sungysang** [comment]
```
List<ACCT_Finder_Request> testRequests = new List<ACCT_Finder_Request>();
List<Account> results = new List<Account>();

Account test = [SELECT Id, Type, Name, BillingLatitude, BillingLongitude
               FROM Account
               WHERE Id = '**INSERT ACCOUNT ID HERE**'];

ACCT_Finder_Request request1 = new ACCT_Finder_Request();
request1.setInputs(test.Id, **INSERT DISTANCE HERE**);

testRequests.add(request1);

results = ACCT_Finder.findAccountsBatch(testRequests)[0];

System.debug('Amount of Accounts returned: ' + results.size());

for (Account result : results) {
    System.debug(result);
}
```

**Comment by Julian88Tex** [comment]
@sungysang did one initial test and it looks good. When you get a chance could you create a PR and assign it to me and Brandon?

**Comment by sungysang** [comment]
@Julian88Tex currently thinking about how sorting would work for return Accounts, believe the best way to implement this would be to have a custom field on the Account to hold the distance value, exactly like the one that will be added to the CSP object. 

Do you feel that the requirement to sort related Accounts by proximity warrants a new custom field? If not, we can sort on the CSP records list since we know for sure that Object will get a Distance custom field.

We could also re-purpose the "Test Distance" field on the Account to accomplish this

**Comment by Julian88Tex** [comment]
@sungysang I'd rather not create a field on Account that is only used for this one operation if possible. Is there no way to store this field information memory when sending it to the flow?

**Comment by sungysang** [comment]
@Julian88Tex As far as I can tell, there's no way to relate a certain value (distance) with each Account as an output unless it's added as a field value. One potential way is via a Map with Account as key and distance as value, but with that route the limitations in Flow would block us as I don't think a Map can be assigned an output value in Flow. Probably would be possible via lwc and maybe Brandon can help out with that? 

Believe the best route would be to display the potential CSP records (and not Accounts) sorted via distance. So instead of Accounts, it would instead create the CSP records (in memory), sort them by distance, and return the 100 closest ones. I could still display the Accounts in debug logs, but the flow would display potential CSP records and their distance next instead of Accounts.

**Comment by Julian88Tex** [comment]
@sungysang Thanks for the info. So I updated the ACs to be more generic in what is returned. The return can be a list of record (don't care which kind) as long as they include an Account of the opposite type, a distance from provided account the matched account, and is sorted by that distance. Doesn't really matter of that record is a CSP or Account or something else as long as it isn't created (committed to database).

Besides that, I would agree that tagging Brandon on this (after he accepts invite) is a good idea so he can provide additional insight.

**Comment by sungysang** [comment]
@Julian88Tex Figured out a way to sort the Accounts before CSP records are created, the Accounts themselves won't show the distance but in debug logs they should be sorted closest to furthest now

**Comment by Julian88Tex** [comment]
@sungysang FYI I updated some of these issues so that we can refine them on Tuesday evening

**Comment by Julian88Tex** [comment]
@sungysang will be closing this out due to an architecture change to use Google Nearby Places API

sorry 😿
