### ISSUE TITLE
Find 20 Closest Unique Churches

### ISSUE THREAD

**Issue by Julian88Tex** [lovinghouston/lwcgoogleplacesbutton#40]
As a user, when I click "Find Churches" I want the five closest unique churches to be created.

Unique = no duplicates of the same church

Given a school with zip & country
And 3 closest existing churches are related through CSP records
And related churches contain the correct names, zip, and country fields
And a duplicates/matching rule exists that matches based on name, zip, and country fields
And duplicates/matching rule is enabled
And debug logs are enabled
When I click "Find Churches"
Then 5 new church & csp records are created
And churches are not duplicates of existing 3
And churches are all closest ones up to 20 closest churches
And churches have valid addresses
And matching results based on the 3 existing churches (aka potential dupes) are viewable in debug logs

Given a school with zip & country
And 20 closest existing churches are related through CSP records
And related churches contain the correct names, zip, and country fields
And a duplicates/matching rule exists that matches based on name, zip, and country fields
And duplicates/matching rule is enabled
And debug logs are enabled
When I click "Find Churches"
Then an error is displayed saying "20 closest Churches have already been found and created."

Given a school with zip & country
And 3 closest existing churches are related through CSP records
And related churches contain the correct names, zip, and country fields
And a duplicates/matching rule exists that matches based on name, zip, and country fields
And duplicates/matching rule is disabled
And debug logs are enabled
When I click "Find Churches"
Then an error is displayed saying "At least 1 Account Duplicate Rule must be enabled. Please ask your admin to enabled in setup."

Given a school with zip & country
And 3 closest existing churches are related through CSP records
And related churches contain the correct names, zip, and country fields
And no duplicates/matching rule exists that matches based on name, zip, and country fields
And debug logs are enabled
When I click "Find Churches"
Then an error is displayed saying "At least 1 Account Duplicate Rule must be enabled. Please ask your admin to enabled in setup."

Test Notes:
- check with churches with same name but different addresses
- check with churches with same addresses but different names
- check with results with invalid addresses (aka no zip and/or country)
- check to make sure it's not filtering out existing churches that don't have CSP records with this school

**Comment by sungysang** [comment]
@Julian88Tex @Rodney-Zhu ready for testing in dev sandbox

**Comment by sungysang** [comment]
Ran into this issue for certain Schools:

`01:57:47:320 USER_DEBUG [74]|DEBUG|Insert failed. First exception on row 0; first error: CANNOT_EXECUTE_FLOW_TRIGGER, We can't save this record because the “CSP Updates” process failed. Give your Salesforce admin these details. This error occurred when the flow tried to update records: INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY: insufficient access rights on cross-reference id: 0031N00001EJVeQ. You can look up ExceptionCode values in the SOAP API Developer Guide. Error ID: 775821272-42842 (-636854535): []`

Recommend deactivating that process or troubleshooting why it's happening before production push

**Comment by sungysang** [comment]
@Julian88Tex @Rodney-Zhu query for finding appropriate schools for testing:

`select id
from account
where type = 'school' and BillingStreet != null`

**Comment by Julian88Tex** [comment]
@sungysang order of displayed CSP fields after clicking button:

CSP name, church name, website, google maps listing, google maps rating, number of google maps reviews, distance

**Comment by rodney-zhu** [comment]
@jonatng @sungysang can you check out this [Blackbox Testing]? I found a duplicate for the same church. (https://docs.google.com/document/d/1YrnynpKkJj-aJD9qLAK5-lj2lB6r9biRLlsT40qTOOg/edit?usp=sharing)

**Comment by sungysang** [comment]
@Rodney-Zhu wow that's a great find, since the duplicate check occurs for existing records, it looks like there's no check for the new churches that are inserted among each other. It would take some extra work to flesh out a method to check within the returned data before it's checked for dupes but I'll create an issue

**Comment by Julian88Tex** [comment]
Closing since we've created new bug tickets based on testing and outside those, functionality is working as expected.
