### ISSUE TITLE
Remove Google API Key from Code and Add to Custom Metadata

### ISSUE THREAD

**Issue by Julian88Tex** [lovinghouston/lwcgoogleplacesbutton#56]
- remove key from GoogleUtility: https://github.com/lovinghouston/lwcgoogleplacesbutton/blob/master/force-app/main/default/classes/GooglePlacesUtility.cls#L86
- create a Custom Metadata Type to store key
- use API Key 4

**Comment by sungysang** [comment]
@Julian88Tex  Metadata Type and record created: https://lovinghouston--partial.lightning.force.com/lightning/setup/CustomMetadata/page?address=%2Fm0B0r0000004Dft

**Comment by jonatng** [comment]
@sungysang 
Test: created a second dummy API key with different numbers.
Result: invalid API key, two different API keys cannot co-exist.
*Can we prevent a second Google API from being created?

**Comment by sungysang** [comment]
@jonatng good test, I don't think there's really any way in terms of validation rules, triggers, etc that we can set on the Custom Metadata Type to prevent users from entering additional records (correct me if I'm wrong @Julian88Tex). But I think this is fine because this is our custom metadata and there's basically no reason someone would need to go in and add another Custom Metadata record unless the current key is expired

**Comment by Julian88Tex** [comment]
Great job on dev @sungysang and great job on testing @jonatng !

Closing this out since it is complete.
